E_Voting_System/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('ec_admin/', include('ec_admin.urls')),
    path('verification/', include('verification.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ec_admin/urls.py
from django.urls import path
from . import views

app_name = "ec_admin"

urlpatterns = [
    path('', views.admin, name="admin"),
    path('add_voter/', views.add_voter, name="add_voter"),
    path('add_candidate/', views.add_candidate, name="add_candidate"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('election_setup/', views.election_setup, name="election_setup"),
    path('election_setup/', views.election_setup, name="election_setup"),
    path('set_up/', views.set_up, name="set_up"),
    path('add_category/', views.add_category, name="add_category"),
    path('voter_register/', views.voter_register, name="voter_register"),
    path('dashboard/', views.dashboard, name="dashboard"),
    path('start_election/', views.start_election, name="start_election"),
    path('edit_voter/<str:voter_id>/', views.edit_voter, name="edit_voter"),
    path('delete/<int:voter_id>/', views.delete, name="delete"),
    path('candidates/', views.candidates, name="candidates"),
    path('close_election/', views.close_election, name="close_election"),
    path('close_election/<int:election_id>/', views.close_election, name="close_election"),
    path('edit_candidate/<int:candidate_id>', views.edit_candidate, name="edit_candidate"),
    path('voter_register_to_pdf', views.voter_register_to_pdf, name="voter_register_to_pdf"),
    path('delete_candidate/<int:candidate_id>/', views.delete_candidate, name="delete_candidate"),
    path('result_pdf/', views.result_pdf, name="result_pdf"),
    path('results/', views.results, name="results"),
]

index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [
    path('', views.login, name="login"),
    path('voting/', views.voting, name="voting"),
    path('voter_logout/', views.voter_logout, name="voter_logout")
]

ec_admin/models.py
from django.db import models

# Create your models here.

index/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date, datetime, timedelta

class Election(models.Model):

    election_name = models.CharField(max_length=50)
    electoral_commission = models.ForeignKey(User, on_delete=models.CASCADE)
    time_to_start = models.DateTimeField()
    time_to_end = models.DateTimeField()
    has_started = models.BooleanField(default=False)
    has_closed = models.BooleanField(default=False)
    real_time_started = models.DateTimeField(auto_now_add=True)
    real_time_ended = models.DateTimeField(null=True, blank=True)


    def __str__(self):
        
        return self.election_name + " " + str(self.time_to_start)
    
    class Meta:

        verbose_name_plural = "Elections"
        ordering = ["election_name", "time_to_start"]
    
    @property

    def time_remaining(self):
        
        time_remaining = self.time_to_end - self.time_to_start

        return time_remaining

class Category(models.Model):

    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=50)

    def __str__(self):
        
        return self.category_name
    
    class Meta:

        verbose_name_plural = "Categories"
        ordering = ["category_name"]

class Candidate(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50)
    dob = models.DateField()
    gender = models.CharField(max_length=1)
    profile_pic = models.ImageField(upload_to="Candidate_Pics")

    def __str__(self):

        return self.first_name + " " + self.last_name

    class Meta:

        ordering = ["category"]
        verbose_name_plural = "Candidates"

class Vote(models.Model):
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    time_voted = models.DateTimeField(auto_now=True)


    def __str__(self):

        return str(self.time_voted)
    
    class Meta:
        ordering = ["category"]
        verbose_name_plural = "Votes"
    
    @property

    def percentage(total, individual_count):

        operation = (self.candidate.count/total) * 100

        return operation

class Voter(models.Model):

    user_name = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=20, null=True, blank=True)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50)
    gender = models.CharField(max_length=1)
    email = models.EmailField()
    dob = models.DateField()
    has_voted = models.BooleanField(default=False)
    isVerified = models.BooleanField(default=False)

    def __str__(self):

        return self.user_name + " " + self.first_name
    
    class Meta:

        verbose_name_plural = "Voters"
        ordering = ["user_name", "first_name", "last_name"]
    
    @property

    def age(self):
        my_date = date.today()
        the_days = my_date - self.dob
        age = int(the_days.days / 365)

        return age


class Current_Election(models.Model):

    election = models.OneToOneField(Election, on_delete=models.CASCADE)


    def __str__(self):

        return str(self.id)
    
    @property
    def the_id(self):

        return str(self.election.id)

ec_admin/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import auth, User
from django.contrib import messages
from index.models import Category, Candidate, Current_Election, Election, Voter, Vote
from django.contrib.auth.models import User
from datetime import datetime, date
from django.core.files.storage import FileSystemStorage
from django.template.loader import get_template
from xhtml2pdf import pisa


def admin(request):

    try:
        request.session["member_id"]
        return redirect("ec_admin:dashboard")
    except KeyError:
        pass
    
    return redirect("ec_admin:login")

def dashboard(request):

    voter = Voter.objects.all()
    total_users = User.objects.all()
    election_count = Election.objects.all()
    count_voters = Voter.objects.filter(has_voted=True)
    
    global election_id
    current = Current_Election.objects.all()

    for id in current:
        election_id = id.election_id

    election = Election.objects.get(id=int(election_id))


    context = {
        'election':election,
        'voter':voter,
        'count_voters':count_voters,
        'election_count':election_count,
    }

    try:
        request.session["member_id"]
        return render(request, "ec_admin/dashboard.html", context)
    except KeyError:
        pass

    return redirect("ec_admin:login")

def add_voter(request):

    if request.method == "POST":

        username = request.POST["username"]
        first_name = request.POST["first_name"]
        middle_name = request.POST["middle_name"]
        last_name = request.POST["last_name"]
        gender = request.POST["gender"]
        email = request.POST["email"]
        dob = request.POST["dob"]

        context = {
            'username':username,
            'first_name':first_name,
            'last_name':last_name,
            'middle_name':middle_name,
            'email':email,
            'gender':gender,
            'dob':dob
        }
        
        if Voter.objects.filter(email=email).exists():

            messages.error(request, "Email already exists")
            return render(request, "ec_admin/add_voter.html", context)
        
        elif Voter.objects.filter(user_name=username).exists():

            messages.error(request, "Username already exists")
            return render(request, "ec_admin/add_voter.html", context)

        else:

            voter = Voter.objects.create(
                user_name=username,
                first_name=first_name,
                middle_name=middle_name,
                last_name=last_name,
                gender=gender,
                dob=dob,
                email=email
            )
            voter.save()

            messages.info(request, "Voter added successfully")
            return redirect("ec_admin:add_voter")

    else:

        try:

            request.session["member_id"]
            return render(request, "ec_admin/add_voter.html")

        except KeyError:
        
            pass

        return redirect("ec_admin:login")


def edit_voter(request, voter_id):

    if request.method == "POST":
        username = request.POST['username']
        first_name = request.POST['first_name']
        middle_name = request.POST['middle_name']
        last_name = request.POST['last_name']
        gender = request.POST['gender']
        dob = request.POST['dob']
        email = request.POST['email']  

        voter = Voter.objects.get(id=voter_id)
        voter.user_name=username
        voter.first_name=first_name
        voter.middle_name=middle_name
        voter.last_name=last_name
        voter.gender=gender
        voter.dob=dob
        voter.email=email
        voter.save()

        return HttpResponse("Changed successfully")

    else:
        

        try:
            request.session["member_id"]
            voter = Voter.objects.get(id=voter_id)
            todays_date = date.today()

            context = {
                'voter':voter,
                'date_today':todays_date
            }

            return render(request, "ec_admin/edit_voter.html", context)

        except KeyError:
            pass
        
        return redirect("ec_admin:login")

    

    

def add_candidate(request):

    global e_id
    current = Current_Election.objects.all()

    for e in current:
        e_id = e.election_id

    election = Election.objects.get(id=e_id)

    context = {
        'election':election,
    }

    if request.method == "POST":

        first_name = request.POST["first_name"]
        last_name = request.POST["last_name"]
        middle_name = request.POST["middle_name"]
        dob = request.POST["dob"]
        gender = request.POST["gender"]
        picture = request.FILES["file"]
        category = request.POST["category"]

        cat = Category.objects.get(id=int(category))

        candidate = Candidate.objects.create(

            first_name=first_name,
            last_name=last_name,
            middle_name=middle_name,
            dob=dob,
            gender=gender,
            profile_pic=picture,
            category=cat

        )
        candidate.save()

        messages.info(request, "Candidate added successfully")
        return redirect("ec_admin:add_candidate")
        
    else:


        try:

            request.session["member_id"]
            return render(request, 'ec_admin/add_candidate.html', context)

        except KeyError:
            
            pass

        return redirect("ec_admin:login")

def election_setup(request):

    user = User.objects.get(id=int(request.session["member_id"]))

    context = {
        'user':user
    }

    try:
        request.session["member_id"]
        return render(request, 'ec_admin/election_setup.html', context)

    except KeyError:
        pass

    return redirect("ec_admin:login")

def set_up(request):

    try:
        
        election_name = request.POST["election"]
        date_start = request.POST["date_to_start"]
        date_end = request.POST["date_to_end"]
        ec_id = request.session["member_id"]

        user = User.objects.get(id=ec_id)

        election = Election.objects.create(
            election_name=election_name,
            electoral_commission=user,
            time_to_start=date_start,
            time_to_end=date_end
        )

        election.save()

        messages.info(request, "Election is set up successfully")

        return redirect("ec_admin:election_setup")

    except KeyError:
        return HttpResponse("Key error...you may need to login before")

def add_category(request):

    try:
        
        category_name = request.POST["category_name"]
        selected_election = request.POST["election"]

        election = Election.objects.get(id=int(selected_election))

        category = Category.objects.create(
            election=election,
            category_name=category_name
        )
        category.save()

        messages.info(request, "Category added successfully")
        return redirect("ec_admin:election_setup")

    except KeyError:
        return HttpResponse("Key Error... maybe you need to login first")


def start_election(request):

    try:
            
        request.session["member_id"]

        election = request.POST["election"]

        current = Current_Election.objects.all()
        current.delete()

        new_election = Election.objects.get(id=int(election))

        set_current = Current_Election.objects.create(
            election_id=new_election.id
        )
        set_current.save()

        set_electon = Election.objects.get(id=int(election))
        set_electon.has_started = True
        set_electon.real_time_started = datetime.today()
        set_electon.save()

        messages.info(request, "Election started successfully")
        return redirect("ec_admin:dashboard")

    except KeyError:
        pass
    return HttpResponse("<h4>Invalid action, maybe you need to login first</h4>")



def voter_register(request):

    voter = Voter.objects.all()

    try:
        request.session["member_id"]

        context = {
            'voter':voter,
        }

        return render(request, "ec_admin/voters.html", context)
        
    except KeyError:
        pass

    return redirect("ec_admin:login")

    
        
    

def login(request):

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            request.session["member_id"] = user.id
            auth.login(request, user)
            return redirect("ec_admin:admin")
        else:
            messages.info(request, "Ivalid login")
            return render(request, "ec_admin/admin_login.html", {'username':username})

    else:
        return render(request, "ec_admin/admin_login.html")

def delete(request, voter_id):

    try:

        request.session["member_id"]
        voter = Voter.objects.get(id=voter_id)
        voter.delete()
        return HttpResponse("Deleted successfully")

    except KeyError:
        pass

    return redirect("ec_admin:login")

def logout(request):
    try:
        auth.logout(request)
        del request.session["member_id"]
    except KeyError:
        pass
    return redirect("ec_admin:login")


def candidates(request):

    try:
        request.session["member_id"]
        candidate = Candidate.objects.all()
        todays_date = date.today()

        context = {
            'candidate':candidate,
            'date':todays_date
        }

        return render(request, "ec_admin/candidate_list.html", context)

    except :
        pass
    
    return redirect("ec_admin:login")

def edit_candidate(request, candidate_id):

    if request.method == "POST":
        
        first_name = request.POST["first_name"]
        middle_name = request.POST["middle_name"]

ec_admin/templates/ec_admin/admin_interface.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    
    {% endblock %}
    <link rel="stylesheet" href="{% static 'index/bs5/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'ec_admin/dashboard.css' %}">



    <link href="{% static 'ec_admin/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'ec_admin/css/sb-admin-2.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this page -->
    <link href="{% static 'ec_admin/vendor/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet">


</head>
<body style="background-color: rgb(230, 230, 230);">

    <style>

        body{
            overflow-x: hidden;
        }

        #side_bar{
        
            line-height: 60px;
            text-align: center;
            background-color:rgb(24, 24, 26);
        }

        a #main_but div:hover{
            background-color: rgb(238, 164, 5);
            color:rgb(24, 24, 26)
        }

        a #main_but div{
            text-align: left;
            margin-left: 25px;
            color: white;
            transition: 0.3s;
        }

        #side_link{
            text-decoration: none;
        }

    </style>

    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="#">E-Voting System</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0" style="--bs-scroll-height: 100px;">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
             
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Admin
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Settings</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'ec_admin:logout' %}">Logout</a></li>
                </ul>
              </li>
              <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Hello, @{{user.username}}</a>
                {% endif %}
              </li>
            </ul>

          </div>
        </div>
      </nav>
    

    <div class="row">


            <div class="col-lg-2 col-md-3" id="side_bar">
                
                <div class="row">
                    <div class="col" style="text-align: left; color: rgb(196, 196, 196); margin-left: 25px; font-family: poppins; font-size: 19px;">
                        EC's PANEL
                    </div>
                </div>


                <a href="{% url 'ec_admin:dashboard' %}" id="side_link" role="button">
                    <div class="row my-1" id="main_but">
                        <div class="col">
                            Dashboard
                        </div>
                    </div>
                </a>

                <a href="{% url 'ec_admin:election_setup' %}" id="side_link">
                    <div class="row my-1" id="main_but">
                        <div class="col">
                            Election Setup
                        </div>
                    </div>
                </a>

                <a href="{% url 'ec_admin:add_candidate' %}" id="side_link" role="button">
                    <div class="row my-1" id="main_but">
                        <div class="col">
                            Add Candidates
                        </div>
                    </div>
                </a>

                <a href="{% url 'ec_admin:candidates' %}" id="side_link" role="button">
                    <div class="row my-1" id="main_but">
                        <div class="col">
                            Candidates List
                        </div>
                    </div>
                </a>

                <a href="{% url 'ec_admin:add_voter' %}" id="side_link" role="button">
                    <div class="row my-1" id="main_but">
                        <div class="col">
                            Add Voter
                        </div>
                    </div>
                </a>


                <a href="{% url 'ec_admin:voter_register' %}" id="side_link" role="button">
                    <div class="row my-1" id="main_but">
                        <div class="col">
                            Voter Register
                        </div>
                    </div>
                </a>

                <a href="{% url 'ec_admin:results' %}" id="side_link">
                    <div class="row my-1" id="main_but">
                        <div class="col">
                            Results
                        </div>
                    </div>
                </a>
                
                <div class="row my-1" id="main_but">
                    <div class="col" style="text-align: center;">
                        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
                            Upload Bulk Voters
                        </button>
                    </div>
                </div>
            

            </div>

            <div class="col-lg-10 col-md-9" style=" border-radius: 5px", id="side_link">

                {% for message in messages %}

                    <div class="alert alert-success d-flex align-items-center alert-dismissible fade show" role="alert" style="margin-top:10px">
                        
                        <div>
                        {{message}}
                        </div>

                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>

                {% endfor %}

                <div class="container">

                    {% block content %}

                    {% endblock %}

                </div>

            </div>

    </div>


    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title">Upload Multiple Voters</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                  </div>

                <div class="modal-body">

                    
                
                        <form action="" class="row" method="" enctype="multipart/form-data">
                            <div class="col-12 mb-3">
                                <label for="file" class="form-label">Excel File</label>
                                <input class="form-control" name="file" type="file" placeholder="Choose file" accept=".xls,.xlsx, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/vnd.ms-excel" >
                            </div>
                
                            <div class="col-12 my-2">
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" style="width: 25%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">25%</div>
                                </div>
                            </div>
                            
                
                            <div class="col-12 mb-4">
                                <button type="submit" class="btn btn-primary">Upload</button>
                            </div>
                        </form>

                </div>
            </div>
        </div>
    </div>

    <div class="row" style="text-align: center">
        <div class="col-12" style="background-color:rgb(24, 24, 26); padding: 10px; color:rgb(230, 230, 230); text-align: center">
            Copyright &copy; ToskyBrown Technology - <span class="text-muted">2021</span> 
        </div>
    </div>

    <script src="{% static 'index/bs5/js/bootstrap.js' %}"></script>

    <script src="{% static 'ec_admin/ajax/jquery.min.js' %}"></script>
 


    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'ec_admin/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'ec_admin/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'ec_admin/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'ec_admin/js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'ec_admin/vendor/datatables/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'ec_admin/vendor/datatables/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'ec_admin/js/demo/datatables-demo.js' %}"></script>

</body>

</html>

ec_admin/templates/ec_admin/election_setup.html
{% extends 'ec_admin/admin_interface.html' %}

{% block title %}
    <title>Election Setup</title>
{% endblock %}


    {% block content %}

    <div class="container" style="background-color: white; padding: 20px; margin-top: 20px; border-radius: 6px; box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2)">

        <h5 class="text-muted">Election Set-Up</h5> <hr>

        <form class="row g-3"  action="{% url 'ec_admin:set_up' %}" method="post" method="post">

            {% csrf_token %}

            <div class="col-12">
                <label for="election_name" class="form-label">Election Name</label>
                <input type="text" class="form-control" name="election" placeholder="Election name" id="election_name" required>
            </div>

            <div class="col-md-6">
                <label for="date_to_start" class="form-label">DateTime-to-Start</label>
                <input type="datetime-local" class="form-control" name="date_to_start" id="date_to_start" required>
            </div>

            
            <div class="col-md-6">
                <label for="date_to_end" class="form-label">DateTime-to-End</label>
                <input type="datetime-local" class="form-control" name="date_to_end" id="date_to_end" required>
            </div>


            <div class="col-12">
                <button class="btn btn-primary">Setup</button>
            </div>
        </form>

    </div>

    <div class="container" style="background-color: white; margin-top: 20px; padding: 20px; border-radius: 6px; box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);">

        <h5 class="text-muted">Add Election Category</h5> <hr>

       <form action="{% url 'ec_admin:add_category' %}" method="post" class="row g-3">

           {% csrf_token %}

            <div class="col-md-4">
                <label for="election" class="form-label">Election</label>
                <select class="form-select" id="election" name="election" required>
                    <option value="">Option...</option>
                    {% for data in user.election_set.all %}
                        <option value="{{data.id}}">{{data.election_name}}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="col-md-8">
                <label for="category_name" class="form-label">Category Name</label>
                <input type="text" class="form-control" name="category_name" id="category_name" placeholder="Category Name" required>
            </div>

            <div class="col-12">
                <button class="btn btn-primary">Save</button>
            </div>
       </form>
    </div>

    {% endblock %}

ec_admin/templates/ec_admin/results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'index/bs5/css/bootstrap.css' %}"/>
    <title>Results{{election.election_name}}</title>
</head>
<body style="background:rgb(224, 224, 224)">


    <div class="container" style="background-color: white;">

        <div class="container mb-3">
            <h4 style="text-align: center;"> {{election.election_name}} RESULTS</h4>
            <h5>Time Started:  {{election.real_time_started}}</h5>
            <h5>Time Ended:  {{election.real_time_ended}}</h5>
            <a style="width: 200px;" href="{% url 'ec_admin:result_pdf' %}" class="btn btn-primary">Print</a> <hr>
        </div>
    
        {% for data in election.category_set.all %}
    
            <div class="container">
    
                <h5 style="text-align: left; color: black; background-color: rgb(236, 236, 236); padding: 7px; font-size: 14px; margin-bottom: 0px;">{{data.category_name}}</h5>
    
                <table class="table table-dark">
                    <th>Total Votes Count</th>
                    <td>{{data.vote_set.count}} </td>
                </table>
            </div>
    
            <div class="container" id="get-list">
                <table class="table mt-3">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Full Name</th>
                            <th>Total Votes</th>
                            <th>Percentage</th>
                        </tr>
                    </thead>
        
                    <tbody>
                        {% for results in data.candidate_set.all %}
                        <tr style="font-weight: bold;" id="table">
                            <td><img src="{{results.profile_pic.url}}" style="width: 200px; border-radius: 70px;"></td>
                            {% if results.middle_name %}
                            <td>{{results.first_name}} {{results.last_name}} {{results.middle_name}}</td>
                            {% else %}
                            <td>{{results.first_name}} {{results.last_name}}</td>
                            {% endif %}
                            <td>{{results.vote_set.count}}</td>
                        </tr>
                        {% endfor %}
                    
                    </tbody>
                </table>
            </div>
            
        {% endfor%}

    </div>

    
    <script src="{% static 'ec_admin/ajax/jquery.min.js' %}"></script>
    <script src="bs5/js/bootstrap.js"></script>
</body>


</html>    