E_Voting_System/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('ec_admin/', include('ec_admin.urls')),
    path('verification/', include('verification.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

index/urls.py
from django.urls import path
from . import views

app_name = "index"

urlpatterns = [
    path('', views.login, name="login"),
    path('voting/', views.voting, name="voting"),
    path('voter_logout/', views.voter_logout, name="voter_logout")
]

index/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date, datetime, timedelta

class Election(models.Model):

    election_name = models.CharField(max_length=50)
    electoral_commission = models.ForeignKey(User, on_delete=models.CASCADE)
    time_to_start = models.DateTimeField()
    time_to_end = models.DateTimeField()
    has_started = models.BooleanField(default=False)
    has_closed = models.BooleanField(default=False)
    real_time_started = models.DateTimeField(auto_now_add=True)
    real_time_ended = models.DateTimeField(null=True, blank=True)


    def __str__(self):
        
        return self.election_name + " " + str(self.time_to_start)
    
    class Meta:

        verbose_name_plural = "Elections"
        ordering = ["election_name", "time_to_start"]
    
    @property

    def time_remaining(self):
        
        time_remaining = self.time_to_end - self.time_to_start

        return time_remaining

class Category(models.Model):

    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    category_name = models.CharField(max_length=50)

    def __str__(self):
        
        return self.category_name
    
    class Meta:

        verbose_name_plural = "Categories"
        ordering = ["category_name"]

class Candidate(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50)
    dob = models.DateField()
    gender = models.CharField(max_length=1)
    profile_pic = models.ImageField(upload_to="Candidate_Pics")

    def __str__(self):

        return self.first_name + " " + self.last_name

    class Meta:

        ordering = ["category"]
        verbose_name_plural = "Candidates"

class Vote(models.Model):
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    time_voted = models.DateTimeField(auto_now=True)


    def __str__(self):

        return str(self.time_voted)
    
    class Meta:
        ordering = ["category"]
        verbose_name_plural = "Votes"
    
    @property

    def percentage(total, individual_count):

        operation = (self.candidate.count/total) * 100

        return operation

class Voter(models.Model):

    user_name = models.CharField(max_length=20, unique=True)
    password = models.CharField(max_length=20, null=True, blank=True)
    first_name = models.CharField(max_length=50)
    middle_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50)
    gender = models.CharField(max_length=1)
    email = models.EmailField()
    dob = models.DateField()
    has_voted = models.BooleanField(default=False)
    isVerified = models.BooleanField(default=False)

    def __str__(self):

        return self.user_name + " " + self.first_name
    
    class Meta:

        verbose_name_plural = "Voters"
        ordering = ["user_name", "first_name", "last_name"]
    
    @property

    def age(self):
        my_date = date.today()
        the_days = my_date - self.dob
        age = int(the_days.days / 365)

        return age


class Current_Election(models.Model):

    election = models.OneToOneField(Election, on_delete=models.CASCADE)


    def __str__(self):

        return str(self.id)
    
    @property
    def the_id(self):

        return str(self.election.id)

index/templates/index/voter_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    
        {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'index/bs5/css/bootstrap.css' %}"/>
</head>
<body style="background-color: rgb(236, 236, 236);">

    <style>
        .form-group{
            margin: 10px;
        }

        .container{
            width: 400px;
            margin-top: 50px;
            box-shadow: 0 8px 16px 0 rgba(0, 0, 0, 0.2);
        }
    </style>

    
    {% for message in messages %}

        <script>alert("{{message}}")</script>
        
    {% endfor %}

    <div class="container px-1" style="background-color: white; padding:10px; border-radius: 8px;">

        <h3 class="lead" style="text-align: center; font-size: 27px;">Voter Login</h3>

        <div style="width: 40%; margin: 0 auto; text-align: center;">
            <img class="img-fluid" src="{% static 'index/my_pic.png' %}" alt="">
        </div>
        
        <form class="form g-3" action="" method="post">

            {% csrf_token %}

            <div class="form-group has-feedback">
                <label for="username">Username</label>
                <input type="text" name="username" placeholder="Enter your index number" required class="form-control" id="username" value="{{username}}">
            </div>

            <div class="form-group has-feedback">
                <label for="password">Password</label>
                <input type="password" name="password" placeholder="Enter your pin" required class="form-control" id="password">
            </div>

            <div class="form-group" style="text-align: center;">
                <button type="submit" class="btn btn-primary" style="text-align: center; width: 40%">Login</button>
            </div>
        </form>


        <hr>

        <footer class="footer" style="text-align: center;"> <small class="text-muted"> Copyright <span>&copy;</span> ToskyBrown Technology - 2021 </small> </footer>

    </div>

    <script src="{% static 'index/bs5/js/bootstrap.js' %}"></script>
</body>
</html>

index/templates/index/voting_interface.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'index/bs5/css/bootstrap.css' %}">
</head>
<body style="overflow-x: hidden;">

    <style>
        [class*="col"]{
            margin-top: 15px;
        }

        label:hover{
            cursor: pointer;
        }

        label:focus{
            border: 1px solid red;
        }

        #my_row{
            background-color: rgb(224, 224, 224);
            padding: 20px;
            margin-top: 10px;
        }

        img{
            height: 200px;
            width: 300px;
            object-fit: contain;
            border-radius: 70px;
        }
    </style>
    
    <div class="row">

        <div class="row" id="my_row" style="font-size: 17px; font-family: poppins; color: rgb(255, 253, 253); background-color:rgb(56, 54, 54)">
            <div class="container-fluid" style="text-align: center;">
                {{election.election_name.upper}} - <span class="text-muted">{{election.time_to_start.date.year}}</span>
            </div>
        </div>

    </div>

    <div class="container">

        

        <form method="post" action="">

            {% csrf_token %}

            {% for ele in election.category_set.all %}

            
            <div class="row" id="my_row" style="font-size: 17px; font-family: poppins; text-align: center; color: rgb(56, 54, 54)">
                {{ele.category_name.upper}}
            </div>

            <div class="row">


                {% for candidate in ele.candidate_set.all %}
                
                <div class="col-md-4 col-sm-6 col-lg-4">
                    <div class="form-check">
                        
                        <label class="form-check-label" for="candidate{{candidate.id}}">

                            <div class="card">

                                <div class="card-body">

                                    {% if candidate.middle_name %}

                                    <div class="card-title">{{candidate.first_name}} {{candidate.middle_name}} {{candidate.last_name}}</div>

                                    {% else %}

                                    <div class="card-title">{{candidate.first_name}} {{candidate.last_name}}</div>

                                    {% endif %}

                                    <img class="card-img-top" src="{{candidate.profile_pic.url}}" id="image">
                                </div>
                                
                            </div>

                        </label>

                        <input class="form-check-input" type="radio" name="{{candidate.category.id}}" id="candidate{{candidate.id}}" autocomplete="off" value="{{candidate.id}}" required>
                      </div>
                </div>
                

                {% endfor %}


            </div>

            <hr>

            {% endfor %} 


            <div class="row" style="text-align: center;">

                <div class="col-md-6">
                    <button class="btn btn-primary btn-lg" style="margin-top: 5px; margin-bottom: 5px;">Vote</button>
                </div>
                
                <div class="col-md-6">
                    <a href="{% url 'index:voter_logout' %}" style="margin-top: 5px; margin-bottom: 5px;" class="btn btn-danger btn-lg">Cancel</a>
                </div>
                
            </div>

        </form>

    </div>

    <script src="{% static 'index/bs5/js/bootstrap.css' %}"></script>
</body>
</html>